# Generated by Django 3.2.4 on 2021-06-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snack',
            old_name='name',
            new_name='location',
        ),
        migrations.AddField(
            model_name='snack',
            name='average_snack_per_sale',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='snack',
            name='hourly_sales',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='snack',
            name='maximum_customers_per_hour',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='snack',
            name='minimum_customers_per_hour',
            field=models.IntegerField(default=0),
        ),
    ]
